(() => {
  'use strict';
  const framePaths = Array.from({length:8},(_,i)=>`assets/frames/frame-${String(i+1).padStart(4,'0')}.jpg`);
  const images = framePaths.map(src => { const image = new Image(); image.src = src; return image; });
  const canvas = document.getElementById('watch-canvas'), ctx = canvas.getContext('2d', {alpha:false});
  const journey = document.querySelector('.watch-journey'), progressBar = document.getElementById('progress-bar'), caption = document.getElementById('stage-caption'), current = {frame:0, target:0, paused:false};
  let raf = 0, lastFrame = -1;
  function fitCanvas(){ const ratio=Math.min(window.devicePixelRatio||1,2), width=canvas.clientWidth||window.innerWidth, height=canvas.clientHeight||window.innerHeight; canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);draw(); }
  function draw(){ const image=images[Math.max(0,Math.min(7,Math.round(current.frame)))];if(!image||!image.complete||!image.naturalWidth){return;}const width=canvas.clientWidth||window.innerWidth,height=canvas.clientHeight||window.innerHeight;ctx.fillStyle='#10100f';ctx.fillRect(0,0,width,height);const scale=Math.max(width/image.naturalWidth,height/image.naturalHeight),drawWidth=image.naturalWidth*scale,drawHeight=image.naturalHeight*scale;ctx.drawImage(image,(width-drawWidth)/2,(height-drawHeight)/2,drawWidth,drawHeight);lastFrame=Math.round(current.frame);}
  function setTarget(){ const rect=journey.getBoundingClientRect(), travel=Math.max(1,journey.offsetHeight-window.innerHeight), p=Math.max(0,Math.min(1,-rect.top/travel)); current.target=p*7;progressBar.style.height=`${p*100}%`;if(p<.18)caption.textContent='SCROLL TO OPEN THE MECHANISM';else if(p<.62)caption.textContent='EVERY PART HAS A PURPOSE';else if(p<.9)caption.textContent='PRECISION, REASSEMBLED';else caption.textContent='THE MOMENT IS YOURS'; }
  function tick(){if(!current.paused){current.frame+=(current.target-current.frame)*.16;if(Math.abs(current.target-current.frame)<.01)current.frame=current.target;}if(Math.round(current.frame)!==lastFrame)draw();raf=requestAnimationFrame(tick);}
  function request(){setTarget();if(!raf)raf=requestAnimationFrame(tick);}
  window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',fitCanvas);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else{raf=0;request();}});
  document.getElementById('prev-frame').addEventListener('click',()=>{current.paused=true;current.target=Math.max(0,current.target-1);current.frame=current.target;draw();});document.getElementById('next-frame').addEventListener('click',()=>{current.paused=true;current.target=Math.min(7,current.target+1);current.frame=current.target;draw();});document.getElementById('pause-frame').addEventListener('click',event=>{current.paused=!current.paused;event.currentTarget.textContent=current.paused?'Resume rotation':'Pause rotation';event.currentTarget.setAttribute('aria-pressed',String(current.paused));if(!current.paused)request();});
  document.getElementById('enquiry-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget),name=String(data.get('name')||'').trim();document.getElementById('form-note').textContent=`Thank you${name?`, ${name}`:''}. Your private enquiry has been noted for this demo.`;event.currentTarget.reset();});document.getElementById('year').textContent=new Date().getFullYear();
  images[0].addEventListener('load',fitCanvas);images.forEach(image=>image.addEventListener('load',draw));if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)current.paused=true;fitCanvas();request();
})();
